### ISSUE TITLE
How to run this crawler in windows CMD?

### ISSUE THREAD

**Issue by VivekShingala** [ashwanthkumar/scraphp#1]
Hello Ashwanth Kumar

Thanks for this project. I am trying to run it in windows localhost using CLI (CMD) but it gives me error that 'scraphp' is not recognised as an internal or external command, operable program or batch file.

In addition to this, how can I run this script through browser itself instead of CLI?

**Comment by ashwanthkumar** [comment]
@VivekShingala This project is not maintained anymore. 

[![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)

It might be because of this [line](https://github.com/ashwanthkumar/scraphp/blob/master/scraphp#L1). Try running it with `php scraphp` (assuming php is in PATH). 

This is not meant to be run from the browser because this is generally a long running process and your request might time out before that (generally). 

PS: I've never tried this on Windows so not exactly sure what the problem it might be.
